---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DOCKERPATH}/sonarr/data:/config
      - ${MEDIAPATH}/tv:/tv #optional
      - ${MEDIAPATH}/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped


