---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DOCKERPATH}/prowlarr/config:/config
      - ${MEDIAPATH}/downloads:/downloads
    ports:
      - 9696:9696
    restart: unless-stopped
    logging:
      options:
        max-size: 50m