---
version: "3.6"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - ${dockerpath}/prowlarr/config:/config
       - ${mediapath}/downloads:/downloads
    ports:
      - 9696:9696
    restart: unless-stopped