---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DOCKERPATH}/radarr/data:/config
      - ${MEDIAPATH}/movies:/movies #optional
      - ${MEDIAPATH}/downloads:/downloads #optional
      - ${MEDIAPATH}/tv:/tv #optional
    ports:
      - 7878:7878
    restart: unless-stopped

