---
version: "3.5"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - ${dockerpath}/radarr/data:/config
      - ${mediapath}/movies:/movies #optional
      - ${mediapath}/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

