---
version: "3.5"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ${dockerpath}/jackett/data:/config
      - ${mediapath}/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
