---
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ${DOCKERPATH}/jackett/data:/config
      - ${MEDIAPATH}/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
