---
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfinmc
    cpus: ${JCPUS} # set by .env file
    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    
    volumes:
      - ${DOCKERPATH}/jellyfin/config:/config
      - ${DOCKERPATH}/jellyfin/cache:/cache
      - ${MEDIAPATH}/tv:/tv
      - ${MEDIAPATH}/movies:/movies
      - ${MEDIAPATH}/music:/music

    ports:
      - 8096:8096
      - 8920:8920
      - 1900:1900/udp
      - 7359:7359/udp

    restart: 'unless-stopped'
    

    # Optional - alternative address used for autodiscovery
 #   environment:
#      - JELLYFIN_PublishedServerUrl=http://example.com
