---
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmissionmc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #optional
      - PASS= #optional
      - WHITELIST=  #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - ${DOCKERPATH}/transmission/data:/config
      - ${MEDIAPATH}/downloads:/downloads
      - ${MEDIAPATH}/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  
